/* SETTINGS */
export const CHANGE_LOCALE = 'CHANGE_LOCALE';
export const SET_SOCKET = 'SET_SOCKET';

/* AUTH */
export const LOGIN_USER_TOKEN = 'LOGIN_USER_TOKEN';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
export const CHECK_TOKEN = 'CHECK_TOKEN';
export const CHECK_TOKEN_SUCCESS = 'CHECK_TOKEN_SUCCESS';
export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS';

/* MENU */
export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES';
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME';
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU';
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES';
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  'MENU_CHANGE_HAS_SUB_ITEM_STATUS';
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const SET_NOTIFICATIONS_UNREAD = 'SET_NOTIFICATIONS_UNREAD';

/* Agency */
export const AGENCY_RESET_ID = 'AGENCY_RESET_ID';
export const AGENCY_FETCH_ID = 'AGENCY_FETCH_ID';
export const AGENCY_APPROVAL_SUCCESS = 'AGENCY_APPROVAL_SUCCESS';
export const AGENCY_APPROVAL_ERROR = 'AGENCY_APPROVAL_ERROR';
export const AGENCY_ACCEPT = 'AGENCY_ACCEPT';
export const AGENCY_REFUSE = 'AGENCY_REFUSE';
export const AGENCY_BLOCK = 'AGENCY_BLOCK';
export const AGENCY_FETCH_ID_SUCCESS = 'AGENCY_FETCH_ID_SUCCESS';
export const AGENCY_FETCH_ID_ERROR = 'AGENCY_FETCH_ID_ERROR';
export const AGENCY_FETCH_LIST = 'AGENCY_FETCH_LIST';
export const AGENCY_FETCH_LIST_SUCCESS = 'AGENCY_FETCH_LIST_SUCCESS';
export const AGENCY_FETCH_LIST_ERROR = 'AGENCY_FETCH_LIST_ERROR';
export const AGENCY_SAVE = 'AGENCY_SAVE_LIST';
export const AGENCY_SAVE_SUCCESS = 'AGENCY_SAVE_SUCCESS';
export const AGENCY_SAVE_ERROR = 'AGENCY_SAVE_ERROR';
export const AGENCY_CLOSE_MODAL = 'AGENCY_CLOSE_MODAL';
export const AGENCY_FETCH_AD_LIST = 'AGENCY_FETCH_AD_LIST';
export const AGENCY_FETCH_AD_LIST_SUCCESS = 'AGENCY_FETCH_AD_LIST_SUCCESS';
export const AGENCY_FETCH_AD_LIST_ERROR = 'AGENCY_FETCH_AD_LIST_ERROR';
export const AGENCY_FETCH_AD_ID = 'AGENCY_FETCH_AD_ID';
export const AGENCY_FETCH_AD_ID_SUCCESS = 'AGENCY_FETCH_AD_ID_SUCCESS';
export const AGENCY_FETCH_AD_ID_ERROR = 'AGENCY_FETCH_AD_ID_ERROR';
export const AGENCY_DISABLE_AD = 'AGENCY_DISABLE_AD';
export const AGENCY_ENABLE_AD = 'AGENCY_ENABLE_AD';
export const AGENCY_ASSIGN_AGENT = 'AGENCY_ASSIGN_AGENT';
export const AGENCY_ASSIGN_AGENT_SUCCESS = 'AGENCY_ASSIGN_AGENT_SUCCESS';
export const AGENCY_ASSIGN_AGENT_ERROR = 'AGENCY_ASSIGN_AGENT_ERROR';
export const AGENCY_UNASSIGN_AGENT = 'AGENCY_UNASSIGN_AGENT';
export const AGENCY_UNASSIGN_AGENT_SUCCESS = 'AGENCY_UNASSIGN_AGENT_SUCCESS';
export const AGENCY_UNASSIGN_AGENT_ERROR = 'AGENCY_UNASSIGN_AGENT_ERROR';
export const AGENCY_FETCH_ASSIGNED_AGENTS = 'AGENCY_FETCH_ASSIGNED_AGENTS';
export const AGENCY_FETCH_ASSIGNED_AGENTS_SUCCESS =
  'AGENCY_FETCH_ASSIGNED_SUCCESS';
export const AGENCY_FETCH_ASSIGNED_AGENTS_ERROR = 'AGENCY_FETCH_ASSIGNED_ERROR';
export const AGENCY_GET_PROFILE = 'AGENCY_GET_PROFILE';
export const AGENCY_GET_PROFILE_SUCCESS = 'AGENCY_GET_PROFILE_SUCCESS';
export const AGENCY_GET_PROFILE_ERROR = 'AGENCY_GET_PROFILE_ERROR';
export const AGENCY_EDIT_PROFILE = 'AGENCY_EDIT_PROFILE';
export const AGENCY_EDIT_PROFILE_SUCCESS = 'AGENCY_EDIT_PROFILE_SUCCESS';
export const AGENCY_EDIT_PROFILE_ERROR = 'AGENCY_EDIT_PROFILE_ERROR';

export const AGENT_RESET_ID = 'AGENT_RESET_ID';
export const AGENT_FETCH_ID = 'AGENT_FETCH_ID';
export const AGENT_APPROVAL_SUCCESS = 'AGENT_APPROVAL_SUCCESS';
export const AGENT_APPROVAL_ERROR = 'AGENT_APPROVAL_ERROR';
export const AGENT_ACCEPT = 'AGENT_ACCEPT';
export const AGENT_REFUSE = 'AGENT_REFUSE';
export const AGENT_BLOCK = 'AGENT_BLOCK';
export const AGENT_FETCH_ID_SUCCESS = 'AGENT_FETCH_ID_SUCCESS';
export const AGENT_FETCH_ID_ERROR = 'AGENT_FETCH_ID_ERROR';
export const AGENT_FETCH_LIST = 'AGENT_FETCH_LIST';
export const AGENT_FETCH_LIST_SUCCESS = 'AGENT_FETCH_LIST_SUCCESS';
export const AGENT_FETCH_LIST_ERROR = 'AGENT_FETCH_LIST_ERROR';
export const AGENT_SAVE = 'AGENT_SAVE_LIST';
export const AGENT_SAVE_SUCCESS = 'AGENT_SAVE_SUCCESS';
export const AGENT_SAVE_ERROR = 'AGENT_SAVE_ERROR';
export const AGENT_SUBSCRIPTION_SAVE = 'AGENT_SUBSCRIPTION_SAVE';
export const AGENT_SUBSCRIPTION_SAVE_SUCCESS =
  'AGENT_SUBSCRIPTION_SAVE_SUCCESS';
export const AGENT_SUBSCRIPTION_SAVE_ERROR = 'AGENT_SUBSCRIPTION_SAVE_ERROR';
export const AGENT_SUBSCRIPTION_SAVE_RESET = 'AGENT_SUBSCRIPTION_SAVE_RESET';
export const AGENT_FETCH_SUBSCRIPTION = 'AGENT_FETCH_SUBSCRIPTION';
export const AGENT_FETCH_SUBSCRIPTION_SUCCESS =
  'AGENT_FETCH_SUBSCRIPTION_SUCCESS';
export const AGENT_SUBSCRIPTION_ENABLE = 'AGENT_SUBSCRIPTION_ENABLE';
export const AGENT_SUBSCRIPTION_ABLE_SUCCESS =
  'AGENT_SUBSCRIPTION_ABLE_SUCCESS';
export const AGENT_SUBSCRIPTION_ABLE_RESET = 'AGENT_SUBSCRIPTION_ABLE_RESET';
export const AGENT_SUBSCRIPTION_DISABLE = 'AGENT_SUBSCRIPTION_DISABLE';
export const AGENT_SUBSCRIPTION_FETCH_ID = 'AGENT_SUBSCRIPTION_FETCH_ID';
export const AGENT_SUBSCRIPTION_FETCH_ID_SUCCESS =
  'AGENT_SUBSCRIPTION_FETCH_ID_SUCCESS';
export const AGENT_SUBSCRIPTION_PUT = 'AGENT_SUBSCRIPTION_PUT';
export const AGENT_SUBSCRIPTION_PUT_SUCCESS = 'AGENT_SUBSCRIPTION_PUT_SUCCESS';
export const AGENT_SUBSCRIPTION_PUT_RESET = 'AGENT_SUBSCRIPTION_PUT_RESET';
export const AGENT_SUBSCRIPTION_PUT_ERROR = 'AGENT_SUBSCRIPTION_PUT_ERROR';
export const AGENT_ASSIGN_AGENCY = 'AGENT_ASSIGN_AGENCY';
export const AGENT_ASSIGN_AGENCY_SUCCESS = 'AGENT_ASSIGN_AGENCY_SUCCESS';
export const AGENT_ASSIGN_AGENCY_ERROR = 'AGENT_ASSIGN_AGENCY_ERROR';
export const AGENT_UNASSIGN_AGENCY = 'AGENT_UNASSIGN_AGENCY';
export const AGENT_UNASSIGN_AGENCY_SUCCESS = 'AGENT_UNASSIGN_AGENCY_SUCCESS';
export const AGENT_UNASSIGN_AGENCY_ERROR = 'AGENT_UNASSIGN_AGENCY_ERROR';
export const AGENT_FETCH_ASSIGNED_AGENCIES = 'AGENT_FETCH_ASSIGNED_AGENCIES';
export const AGENT_FETCH_ASSIGNED_AGENCIES_SUCCESS =
  'AGENT_FETCH_ASSIGNED_SUCCESS';
export const AGENT_FETCH_ASSIGNED_AGENTS_ERROR = 'AGENT_FETCH_ASSIGNED_ERROR';

export const USER_APPROVAL_SUCCESS = 'USER_APPROVAL_SUCCESS';
export const USER_APPROVAL_ERROR = 'USER_APPROVAL_ERROR';
export const USER_ACCEPT = 'USER_ACCEPT';
export const USER_REFUSE = 'USER_REFUSE';
export const USER_BLOCK = 'USER_BLOCK';
export const USER_RESET_ID = 'USER_RESET_ID';
export const USER_FETCH_ID = 'USER_FETCH_ID';
export const USER_FETCH_ID_SUCCESS = 'USER_FETCH_ID_SUCCESS';
export const USER_FETCH_ID_ERROR = 'USER_FETCH_ID_ERROR';
export const USER_FETCH_LIST = 'USER_FETCH_LIST';
export const USER_FETCH_LIST_SUCCESS = 'USER_FETCH_LIST_SUCCESS';
export const USER_FETCH_LIST_ERROR = 'USER_FETCH_LIST_ERROR';
export const USER_SAVE = 'USER_SAVE_LIST';
export const USER_SAVE_SUCCESS = 'USER_SAVE_SUCCESS';
export const USER_SAVE_ERROR = 'USER_SAVE_ERROR';
export const USER_FETCH_AD_LIST = 'USER_FETCH_AD_LIST';
export const USER_FETCH_AD_LIST_SUCCESS = 'USER_FETCH_AD_LIST_SUCCESS';
export const USER_FETCH_AD_LIST_ERROR = 'USER_FETCH_AD_LIST_ERROR';
export const USER_FETCH_AD_ID = 'USER_FETCH_AD_ID';
export const USER_FETCH_AD_ID_SUCCESS = 'USER_FETCH_AD_ID_SUCCESS';
export const USER_FETCH_AD_ID_ERROR = 'USER_FETCH_AD_ID_ERROR';
export const USER_DISABLE_AD = 'USER_DISABLE_AD';
export const USER_ENABLE_AD = 'USER_ENABLE_AD';

export const USERS_DISABLE = 'USERS_DISABLE';
export const USERS_ENABLE = 'USERS_ENABLE';
export const USERS_ABLE_SUCCESS = 'USERS_ABLE_SUCCESS';
export const USERS_ABLE_RESET = 'USERS_ABLE_RESET';

/* Agency Subscription */
export const AGENCY_SUBSCRIPTION_RESET_ID = 'AGENCY_SUBSCRIPTION_RESET_ID';
export const AGENCY_SUBSCRIPTION_FETCH_ID = 'AGENCY_SUBSCRIPTION_FETCH_ID';
export const AGENCY_SUBSCRIPTION_FETCH_ID_SUCCESS =
  'AGENCY_SUBSCRIPTION_FETCH_ID_SUCCESS';
export const AGENCY_SUBSCRIPTION_FETCH_ID_ERROR =
  'AGENCY_SUBSCRIPTION_FETCH_ID_ERROR';
export const AGENCY_SUBSCRIPTION_FETCH_LIST = 'AGENCY_SUBSCRIPTION_FETCH_LIST';
export const AGENCY_SUBSCRIPTION_FETCH_LIST_SUCCESS =
  'AGENCY_SUBSCRIPTION_FETCH_LIST_SUCCESS';
export const AGENCY_SUBSCRIPTION_FETCH_LIST_ERROR =
  'AGENCY_SUBSCRIPTION_FETCH_LIST_ERROR';
export const AGENCY_SUBSCRIPTION_SAVE = 'AGENCY_SUBSCRIPTION_SAVE_LIST';
export const AGENCY_SUBSCRIPTION_SAVE_SUCCESS =
  'AGENCY_SUBSCRIPTION_SAVE_SUCCESS';
export const AGENCY_SUBSCRIPTION_SAVE_ERROR = 'AGENCY_SUBSCRIPTION_SAVE_ERROR';
export const AGENCY_SUBSCRIPTION_EDIT = 'AGENCY_SUBSCRIPTION_EDIT_LIST';
export const AGENCY_SUBSCRIPTION_EDIT_SUCCESS =
  'AGENCY_SUBSCRIPTION_EDIT_SUCCESS';
export const AGENCY_SUBSCRIPTION_EDIT_ERROR = 'AGENCY_SUBSCRIPTION_EDIT_ERROR';
export const AGENCY_SUBSCRIPTION_DISABLE = 'AGENCY_SUBSCRIPTION_DISABLE';
export const AGENCY_SUBSCRIPTION_ENABLE = 'AGENCY_SUBSCRIPTION_ENABLE';
export const AGENCY_SUBSCRIPTION_ABLE_SUCCESS =
  'AGENCY_SUBSCRIPTION_ABLE_SUCCESS';
export const AGENCY_SUBSCRIPTION_ABLE_RESET = 'AGENCY_SUBSCRIPTION_ABLE_RESET';
export const AGENCY_SUBSCRIPTION_EDIT_RESET = 'AGENCY_SUBSCRIPTION_EDIT_RESET';
export const AGENCY_SUBSCRIPTION_ASSIGN = 'AGENCY_SUBSCRIPTION_ASSIGN_LIST';
export const AGENCY_SUBSCRIPTION_ASSIGN_SUCCESS =
  'AGENCY_SUBSCRIPTION_ASSIGN_SUCCESS';
export const AGENCY_SUBSCRIPTION_ASSIGN_ERROR =
  'AGENCY_SUBSCRIPTION_ASSIGN_ERROR';
export const ACTUAL_SUBSCRIPTION = 'ACTUAL_SUBSCRIPTION';
export const ACTUAL_SUBSCRIPTION_SUCCESS = 'ACTUAL_SUBSCRIPTION_SUCCESS';
export const ACTUAL_SUBSCRIPTION_ERROR = 'ACTUAL_SUBSCRIPTION_ERROR';
export const AGENCY_REQUEST_AGENT = 'AGENCY_REQUEST_AGENT';
export const AGENCY_REQUEST_AGENT_SUCCESS = 'AGENCY_REQUEST_AGENT_SUCCESS';
export const AGENCY_REQUEST_AGENT_ERROR = 'AGENCY_REQUEST_AGENT_ERROR';
// Rating
export const USER_RATING_FETCH_ID = 'USER_RATING_FETCH_ID';
export const USER_RATING_FETCH_ID_SUCCESS = 'USER_RATING_FETCH_ID_SUCCESS';
export const USER_RATING_FETCH_ID_ERROR = 'USER_RATING_FETCH_ID_ERROR';
export const USER_RATING_FETCH_LIST = 'USER_RATING_FETCH_LIST';
export const USER_RATING_FETCH_LIST_SUCCESS = 'USER_RATING_FETCH_LIST_SUCCESS';
export const USER_RATING_FETCH_LIST_ERROR = 'USER_RATING_FETCH_ID';
export const RATING_READ = 'RATING_READ';
export const RATING_READ_SUCCESS = 'RATING_READ_SUCCESS';
export const RATING_READ_ERROR = 'RATING_READ_ERROR';
export const AGENCY_RATING_FETCH_ID = 'AGENCY_RATING_FETCH_ID';
export const AGENCY_RATING_FETCH_ID_SUCCESS = 'AGENCY_RATING_FETCH_ID_SUCCESS';
export const AGENCY_RATING_FETCH_ID_ERROR = 'AGENCY_RATING_FETCH_ID_ERROR';
export const AGENCY_RATING_FETCH_LIST = 'AGENCY_RATING_FETCH_LIST';
export const AGENCY_RATING_FETCH_LIST_SUCCESS =
  'AGENCY_RATING_FETCH_LIST_SUCCESS';
export const AGENCY_RATING_FETCH_LIST_ERROR = 'AGENCY_RATING_FETCH_ID';
export const AGENCY_RATING_READ = 'AGENCY_RATING_READ';
export const AGENCY_RATING_READ_SUCCESS = 'AGENCY_RATING_READ_SUCCESS';
export const AGENT_RATING_FETCH_ID = 'AGENT_RATING_FETCH_ID';
export const AGENT_RATING_FETCH_ID_SUCCESS = 'AGENT_RATING_FETCH_ID_SUCCESS';
export const AGENT_RATING_FETCH_ID_ERROR = 'AGENT_RATING_FETCH_ID_ERROR';
export const AGENT_RATING_FETCH_LIST = 'AGENT_RATING_FETCH_LIST';
export const AGENT_RATING_FETCH_LIST_SUCCESS =
  'AGENT_RATING_FETCH_LIST_SUCCESS';
export const AGENT_RATING_FETCH_LIST_ERROR = 'AGENT_RATING_FETCH_ID';
export const AGENT_RATING_READ = 'AGENT_RATING_READ';
export const AGENT_RATING_READ_SUCCESS = 'AGENT_RATING_READ_SUCCESS';

// Transactions
export const USER_TRANSACTION_FETCH_ID = 'USER_TRANSACTION_FETCH_ID';
export const USER_TRANSACTION_FETCH_ID_SUCCESS =
  'USER_TRANSACTION_FETCH_ID_SUCCESS';
export const USER_TRANSACTION_FETCH_ID_ERROR =
  'USER_TRANSACTION_FETCH_ID_ERROR';
export const USER_TRANSACTION_FETCH_LIST = 'USER_TRANSACTION_FETCH_LIST';
export const USER_TRANSACTION_FETCH_LIST_SUCCESS =
  'USER_TRANSACTION_FETCH_LIST_SUCCESS';
export const USER_TRANSACTION_FETCH_LIST_ERROR = 'USER_TRANSACTION_FETCH_ID';
export const AGENCY_TRANSACTION_FETCH_ID = 'AGENCY_TRANSACTION_FETCH_ID';
export const AGENCY_TRANSACTION_FETCH_ID_SUCCESS =
  'AGENCY_TRANSACTION_FETCH_ID_SUCCESS';
export const AGENCY_TRANSACTION_FETCH_ID_ERROR =
  'AGENCY_TRANSACTION_FETCH_ID_ERROR';
export const AGENCY_TRANSACTION_FETCH_LIST = 'AGENCY_TRANSACTION_FETCH_LIST';
export const AGENCY_TRANSACTION_FETCH_LIST_SUCCESS =
  'AGENCY_TRANSACTION_FETCH_LIST_SUCCESS';
export const AGENCY_TRANSACTION_FETCH_LIST_ERROR =
  'AGENCY_TRANSACTION_FETCH_ID';
export const AGENT_TRANSACTION_FETCH_ID = 'AGENT_TRANSACTION_FETCH_ID';
export const AGENT_TRANSACTION_FETCH_ID_SUCCESS =
  'AGENT_TRANSACTION_FETCH_ID_SUCCESS';
export const AGENT_TRANSACTION_FETCH_ID_ERROR =
  'AGENT_TRANSACTION_FETCH_ID_ERROR';
export const AGENT_TRANSACTION_FETCH_LIST = 'AGENT_TRANSACTION_FETCH_LIST';
export const AGENT_TRANSACTION_FETCH_LIST_SUCCESS =
  'AGENT_TRANSACTION_FETCH_LIST_SUCCESS';
export const AGENT_TRANSACTION_FETCH_LIST_ERROR = 'AGENT_TRANSACTION_FETCH_ID';

export const PLANS_RESET_ID = 'PLANS_RESET_ID';
export const PLANS_FETCH_ID = 'PLANS_FETCH_ID';
export const PLANS_FETCH_ID_SUCCESS = 'PLANS_FETCH_ID_SUCCESS';
export const PLANS_FETCH_ID_ERROR = 'PLANS_FETCH_ID_ERROR';
export const PLANS_FETCH_LIST = 'PLANS_FETCH_LIST';
export const PLANS_FETCH_LIST_SUCCESS = 'PLANS_FETCH_LIST_SUCCESS';
export const PLANS_FETCH_LIST_ERROR = 'PLANS_FETCH_LIST_ERROR';
export const PLANS_SAVE = 'PLANS_SAVE';
export const PLANS_SAVE_SUCCESS = 'PLANS_SAVE_SUCCESS';
export const PLANS_SAVE_ERROR = 'PLANS_SAVE_ERROR';
export const PLANS_DISABLE = 'PLANS_DISABLE';
export const PLANS_ENABLE = 'PLANS_ENABLE';
export const PLANS_EDIT = 'PLANS_EDIT';
export const PLANS_ABLE_SUCCESS = 'PLANS_ABLE_SUCCESS';
export const PLANS_ABLE_RESET = 'PLANS_ABLE_RESET';

// ADs
export const AD_FETCH_CONSTANTS = 'AD_FETCH_CONSTANTS';
export const AD_FETCH_CONSTANTS_SUCCESS = 'AD_FETCH_CONSTANTS_SUCCESS';
export const AD_FETCH_CONSTANTS_ERROR = 'AD_FETCH_CONSTANTS_ERROR';
export const AD_FETCH_LIST = 'AD_FETCH_LIST';
export const AD_FETCH_LIST_SUCCESS = 'AD_FETCH_LIST_SUCCESS';
export const AD_FETCH_LIST_ERROR = 'AD_FETCH_LIST_ERROR';
export const AD_FETCH_ID = 'AD_FETCH_ID';
export const AD_FETCH_ID_SUCCESS = 'AD_FETCH_ID_SUCCESS';
export const AD_FETCH_ID_ERROR = 'AD_FETCH_ID_ERROR';
export const AD_SAVE = 'AD_SAVE';
export const AD_SAVE_SUCCESS = 'AD_SAVE_SUCCESS';
export const AD_SAVE_ERROR = 'AD_SAVE_ERROR';
export const AD_ENABLE = 'AD_ENABLE';
export const AD_ENABLE_SUCCESS = 'AD_ENABLE_SUCCESS';
export const AD_ENABLE_ERROR = 'AD_ENABLE_ERROR';
export const AD_DISABLE = 'AD_DISABLE';
export const AD_DISABLE_SUCCESS = 'AD_DISABLE_SUCCESS';
export const AD_DISABLE_ERROR = 'AD_DISABLE_ERROR';

export const AD_FETCH_CEP = 'AD_FETCH_CEP';
export const AD_FETCH_CEP_SUCCESS = 'AD_FETCH_CEP_SUCCESS';
export const AD_FETCH_CEP_ERROR = 'AD_FETCH_CEP_ERROR';

export const AD_SOLD = 'AD_SOLD';
export const AD_SOLD_SUCCESS = 'AD_SOLD_SUCCESS';
export const AD_SOLD_ERROR = 'AD_SOLD_ERROR';

export const AD_EDIT = 'AD_EDIT';
export const AD_EDIT_SUCCESS = 'AD_EDIT_SUCCESS';
export const AD_EDIT_ERROR = 'AD_EDIT_ERROR';

export const AD_REQUEST_LIST = 'AD_REQUEST_LIST';
export const AD_REQUEST_LIST_SUCCESS = 'AD_REQUEST_LIST_SUCCESS';
export const AD_REQUEST_LIST_ERROR = 'AD_REQUEST_LIST_ERROR';
export const AD_REQUEST_ID = 'AD_REQUEST_ID';
export const AD_REQUEST_ID_SUCCESS = 'AD_REQUEST_ID_SUCCESS';
export const AD_REQUEST_ID_ERROR = 'AD_REQUEST_ID_ERROR';
export const AD_ACCEPT_REQUEST = 'AD_ACCEPT_REQUEST';
export const AD_ACCEPT_REQUEST_SUCCESS = 'AD_ACCEPT_REQUEST_SUCCESS';
export const AD_ACCEPT_REQUEST_ERROR = 'AD_ACCEPT_REQUEST_ERROR';
export const AD_REMOVE_REQUEST = 'AD_REMOVE_REQUEST';
export const AD_REMOVE_REQUEST_SUCCESS = 'AD_REMOVE_REQUEST_SUCCESS';
export const AD_REMOVE_REQUEST_ERROR = 'AD_REMOVE_REQUEST_ERROR';
export const AD_ACCEPT_SOLD_REQUEST = 'AD_ACCEPT_SOLD_REQUEST';
export const AD_ACCEPT_SOLD_REQUEST_SUCCESS = 'AD_ACCEPT_SOLD_REQUEST_SUCCESS';
export const AD_ACCEPT_SOLD_REQUEST_ERROR = 'AD_ACCEPT_SOLD_REQUEST_ERROR';
export const AD_REMOVE_SOLD_REQUEST = 'AD_REMOVE_SOLD_REQUEST';
export const AD_REMOVE_SOLD_REQUEST_SUCCESS = 'AD_REMOVE_SOLD_REQUEST_SUCCESS';
export const AD_REMOVE_SOLD_REQUEST_ERROR = 'AD_REMOVE_SOLD_REQUEST_ERROR';

export const ISSUES_FETCH = 'ISSUES_FETCH';
export const ISSUES_FETCH_SUCCESS = 'ISSUES_FETCH_SUCCESS';
export const ISSUES_FETCH_ERROR = 'ISSUES_FETCH_ERROR';
export const ISSUES_FETCH_ID = 'ISSUES_FETCH_ID';
export const ISSUES_FETCH_ID_SUCCESS = 'ISSUES_FETCH_ID_SUCCESS';
export const ISSUES_FETCH_ID_ERROR = 'ISSUES_FETCH_ID_ERROR';
export const ISSUE_READ = 'ISSUE_READ';
export const ISSUE_READ_SUCCESS = 'ISSUE_READ_SUCCESS';
export const ISSUE_READ_ERROR = 'ISSUE_READ_ERROR';

// Agent_Imob

export const IMOB_AGENT_FETCH_LIST = 'IMOB_AGENT_FETCH_LIST';
export const IMOB_AGENT_FETCH_LIST_SUCCESS = 'IMOB_AGENT_FETCH_LIST_SUCCESS';
export const IMOB_AGENT_FETCH_LIST_ERROR = 'IMOB_AGENT_FETCH_LIST_ERROR';
export const IMOB_AGENT_APPROVE_ASSIGN = 'IMOB_AGENT_APPROVE_ASSIGN';
export const IMOB_AGENT_APPROVE_ASSIGN_SUCCESS =
  'IMOB_AGENT_APPROVE_ASSIGN_SUCCESS';
export const IMOB_AGENT_APPROVE_ASSIGN_ERROR =
  'IMOB_AGENT_APPROVE_ASSIGN_ERROR';
export const IMOB_AGENT_APPROVE_ASSIGN_REFRESH_SUCCESS =
  'IMOB_AGENT_APPROVE_ASSIGN_REFRESH_SUCCESS';
export const IMOB_AGENT_UNASSIGN = 'IMOB_AGENT_UNASSIGN';
export const IMOB_AGENT_UNASSIGN_SUCCESS = 'IMOB_AGENT_UNASSIGN_SUCCESS';
export const IMOB_AGENT_UNASSIGN_ERROR = 'IMOB_AGENT_UNASSIGN_ERROR';
export const IMOB_AGENT_UNASSIGN_REFRESH_SUCCESS =
  'IMOB_AGENT_UNASSIGN_REFRESH_SUCCESS';
export const IMOB_SEARCH_FETCH_LIST = 'IMOB_SEARCH_FETCH_LIST';
export const IMOB_SEARCH_FETCH_LIST_SUCCESS = 'IMOB_SEARCH_FETCH_LIST_SUCCESS';
export const IMOB_SEARCH_FETCH_LIST_ERROR = 'IMOB_SEARCH_FETCH_LIST_ERROR';

export const CRECI_LIST = 'CRECI_LIST';
export const CRECI_LIST_SUCCESS = 'CRECI_LIST_SUCCESS';
export const CRECI_LIST_ERROR = 'CRECI_LIST_ERROR';

export const CRECI_BY_ID = 'CRECI_BY_ID';
export const CRECI_BY_ID_SUCCESS = 'CRECI_BY_ID_SUCCESS';
export const CRECI_BY_ID_ERROR = 'CRECI_BY_ID_ERROR';

export const CRECI_APPROVE = 'CRECI_APPROVE';
export const CRECI_APPROVE_SUCCESS = 'CRECI_APPROVE_SUCCESS';
export const CRECI_APPROVE_ERROR = 'CRECI_APPROVE_ERROR';

export const CRECI_REPROVE = 'CRECI_REPROVE';
export const CRECI_REPROVE_SUCCESS = 'CRECI_REPROVE_SUCCESS';
export const CRECI_REPROVE_ERROR = 'CRECI_REPROVE_ERROR';

// dashboard

export const DASHBOARD_LIST = 'DASHBOARD_LIST';
export const DASHBOARD_LIST_SUCCESS = 'DASHBOARD_LIST_SUCCESSS';
export const DASHBOARD_LIST_ERROR = 'DASHBOARD_LIST_ERROR';

export const IMOB_DASHBOARD_GET_AGENTS = 'IMOB_DASHBOARD_GET_AGENT';
export const IMOB_DASHBOARD_GET_AGENTS_SUCCESS =
  'IMOB_DASHBOARD_GET_AGENT_SUCCESS';
export const IMOB_DASHBOARD_GET_AGENTS_ERROR = 'IMOB_DASHBOARD_GET_AGENT_ERROR';

export * from './menu/actions';
export * from './settings/actions';
export * from './auth/actions';
